"use client";
import { useState, useTransition } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import type { Issue, RankingResponse, RankingType, Trend } from "@/types";
import { Header } from "./Header";
import { IssueCard } from "./IssueCard";
import { AdSlot } from "./AdSlot";
const types:{value:RankingType;label:string}[]=[{value:"REALTIME",label:"실시간"},{value:"RISING",label:"급상승"},{value:"TODAY",label:"오늘"},{value:"WEEKLY",label:"주간"}];
const categories=["전체","정치","경제","사회","국제","연예","스포츠","IT·과학","생활","문화","건강"];
export function HomeClient({initial,trends}:{initial:RankingResponse;trends:Trend[]}){const [items,setItems]=useState<Issue[]>(initial.items);const [type,setType]=useState<RankingType>("REALTIME");const [category,setCategory]=useState("전체");const [expanded,setExpanded]=useState(false);const [visible,setVisible]=useState(10);const [pending,startTransition]=useTransition();function load(t:RankingType,c:string){setType(t);setCategory(c);setVisible(10);startTransition(async()=>setItems((await api.rankings(t,c==="전체"?undefined:c)).items));}return <main className="shell"><Header/><div className="breaking"><b>속보</b><span>수도권 호우특보 확대…재난 대응 2단계</span></div><section className="trends"><header><i/><h2>실시간 인기 검색어</h2><small>5분 전 갱신</small></header><div className="trend-grid">{trends.slice(0,expanded?10:5).map(t=><Link href={`/search?query=${encodeURIComponent(t.keyword)}`} key={t.keyword}><b>{t.rank}</b><span>{t.keyword}</span><em className={t.status.toLowerCase()}>{t.status==="NEW"?"NEW":t.status==="SAME"?"―":`${t.status==="UP"?"▲":"▼"}${t.rankChange}`}</em></Link>)}</div><button className="expand" onClick={()=>setExpanded(v=>!v)}>{expanded?"접기 ︿":"10위까지 전체 보기 ﹀"}</button></section><AdSlot position="HOME_TOP"/><div className="sticky-tabs"><nav className="tabs">{types.map(t=><button key={t.value} className={type===t.value?"active":""} onClick={()=>load(t.value,category)}>{t.label}</button>)}</nav><nav className="chips">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>load(type,c)}>{c}</button>)}</nav></div><section className="ranking-head"><h1>{category==="전체"?"실시간 종합 순위":`${category} 순위`}</h1><p>여러 출처를 이슈별로 묶었어요</p></section>{pending?<div className="loading-list">{Array.from({length:5},(_,i)=><div className="skeleton card" key={i}/>)}</div>:items.length?<section className="issue-list">{items.slice(0,visible).map(i=><IssueCard issue={i} key={i.id}/>)}</section>:<section className="empty"><b>표시할 이슈가 없습니다</b><p>다른 카테고리를 선택해 보세요.</p></section>}{visible<items.length&&<button className="more" onClick={()=>setVisible(v=>v+10)}>다음 순위 더 보기</button>}<AdSlot position="HOME_RANKING_MIDDLE"/><nav className="bottom"><Link className="active" href="/">⌂<span>홈</span></Link><a href="#category">▦<span>카테고리</span></a><Link href="/search">⌕<span>검색</span></Link><button onClick={()=>load("RISING","전체")}>↗<span>급상승</span></button><button>⚙<span>설정</span></button></nav></main>;}
