import type { Article, Issue, IssueDetail, RankingResponse, RankingType, SearchResponse, Timeline, Trend } from "@/types";
const categories = ["사회", "IT·과학", "스포츠", "경제", "정치", "국제", "연예", "생활", "문화", "건강"];
const titles = ["수도권 집중호우, 도로 통제와 지하철 지연","삼성전자, 온디바이스 AI 강화한 신형 스마트폰 공개","프로야구 후반기 순위 경쟁 본격화","한국은행 기준금리 동결, 하반기 인하 가능성은","정부, 도심 주택 공급 확대 방안 발표","아시아 증시 일제히 반등, 글로벌 기술주 강세","톱배우 깜짝 결혼 발표, 동료 축하 이어져","제8호 태풍 북상 중, 주말 남부 영향 가능성","한국 영화 신작, 개봉 첫날 박스오피스 1위","폭염 속 온열질환 주의, 낮 시간 야외활동 줄여야","비트코인 변동성 확대, 주요 지지선 공방","축구 국가대표 명단 발표, 젊은 선수 대거 발탁","국내 연구진, 차세대 배터리 수명 개선 기술 개발","국회 민생 법안 처리 일정 조율","주요국 기후 정상회의, 공동 대응안 논의"];
export const mockIssues: Issue[] = titles.map((title, index) => ({ id:index+1,rank:index+1,previousRank:index%5===1?0:Math.max(1,index+(index%3)),rankStatus:index%5===1?"NEW":index%3===0?"UP":index%3===1?"DOWN":"SAME",category:categories[index%10],title,aiSummary:index===0?"서울 전역에 강한 비가 이어지며 주요 도로와 일부 지하철 운행이 제한되고 있습니다.":`${title} 관련 핵심 내용을 여러 공개 출처를 바탕으로 정리했습니다.`,interestScore:Math.round((94.3-index*2.1)*10)/10,articleCount:57-index*2,publisherCount:23-Math.floor(index/2),pageViews:12430-index*300,uniqueViews:8910-index*240,outboundClicks:730-index*16,searchCount:980-index*28,articleVelocity:180-index*9,updatedAt:new Date(Date.now()-index*7*60000).toISOString(),tags:[categories[index%10],index===0?"집중호우":"주요이슈",index===1?"삼성전자":"실시간"] }));
const publishers=["연합뉴스","KBS","MBC","SBS","한겨레","경향신문","한국일보","서울신문","매일경제","전자신문"];
export const mockArticles:Article[]=mockIssues.flatMap((issue,i)=>Array.from({length:4},(_,j)=>({id:i*4+j+1,issueId:issue.id,publisher:publishers[(i+j)%10],title:`${["속보","종합","분석","현장"][j]} | ${issue.title}`,originalUrl:`https://example.com/news/${i*4+j+1}`,publishedAt:new Date(Date.now()-(i*9+j*14)*60000).toISOString(),officialSource:j===0&&i%4===0})));
export const mockTrends:Trend[]=["수도권 폭우","삼성전자 AI폰","프로야구 순위","기준금리","태풍 경로","부동산 정책","비트코인","축구 국가대표","배우 결혼","신작 영화"].map((keyword,index)=>({rank:index+1,previousRank:index%4===1?0:index+(index%3),status:index%4===1?"NEW":index%3===0?"UP":index%3===1?"DOWN":"SAME",rankChange:index%3,keyword,searchCount:220-index*13}));
export function mockRankings(type:RankingType,category?:string):RankingResponse{const items=category?mockIssues.filter(i=>i.category===category):mockIssues;return{items,total:items.length,type,category,calculatedAt:new Date().toISOString()};}
export function mockDetail(id:number):IssueDetail{const issue=mockIssues.find(i=>i.id===id)??mockIssues[0];return{issue,keyFacts:["복수의 공개 출처에서 공통 사실을 확인했습니다.","관계 기관의 공식 발표가 추가됐습니다.","새로운 정보에 따라 요약이 갱신됩니다."],entities:[{type:"ORGANIZATION",name:"관계 기관"},{type:"LOCATION",name:id===1?"수도권":"대한민국"}],relatedIssueIds:[2,4,8].filter(x=>x!==id)};}
export function mockTimeline(id:number):Timeline[]{return["관련 소식 최초 보도","관계 기관 공식 발표","후속 상황 업데이트"].map((title,index)=>({id:id*10+index,issueId:id,eventTime:new Date(Date.now()-(3-index)*3600000).toISOString(),title,description:"관련 주요 상황이 확인됐습니다.",displayOrder:index+1}));}
export function mockSearch(query:string):SearchResponse{const q=query.toLowerCase().replaceAll(" ","");const issues=mockIssues.filter(i=>`${i.title}${i.aiSummary}${i.tags.join("")}`.toLowerCase().replaceAll(" ","").includes(q));const ids=new Set(issues.map(i=>i.id));const articles=mockArticles.filter(a=>a.title.toLowerCase().replaceAll(" ","").includes(q)||ids.has(a.issueId));return{query,normalizedQuery:query.trim(),issues,articles,total:issues.length+articles.length};}
